=== dorohovichandrey/xml_xsd_parsing/data/gem.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/gems"
        xmlns:tns="http://www.example.com/gems"
        elementFormDefault="qualified">
    <element name="gem" type="tns:Gem" abstract="true"></element>
    <element name="precious-gem" type="tns:PreciousGem" substitutionGroup="tns:gem"></element>
    <element name="semiprecious-gem" type="tns:SemipreciousGem" substitutionGroup="tns:gem"></element>

    <element name="gems">
        <complexType>
            <sequence>
                <element ref="tns:gem" minOccurs="2" maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <complexType name="Gem">
        <sequence>
            <element name="name" type="string" />
            <element name="origin" type="tns:Origin"/>
            <element name="visual-parameters" type="tns:VisualParameters" />
            <element name="value-in-carat">
                <simpleType>
                    <restriction base="positiveInteger">
                        <maxInclusive value="150"></maxInclusive>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    <attribute name="gem-id" type="tns:GemId" use="required" />
    </complexType>

    <simpleType name="GemId">
        <restriction base="ID">
            <pattern value="([a-zA-Z])[a-zA-Z0-9]{1,19}"/>
        </restriction>
    </simpleType>


    <complexType name="Origin">
        <sequence>
            <element name="country" type="string"/>
            <element name="city" type="string" />
        </sequence>
    </complexType>

    <complexType name="VisualParameters">
        <sequence>
            <element name="colour" type="string" />
            <element name="transparency-in-percents">
                <simpleType>
                    <restriction base="nonNegativeInteger">
                        <maxInclusive value="100"></maxInclusive>
                    </restriction>
                </simpleType>
            </element>
            <element name="number-of-verges">
                <simpleType>
                    <restriction base="positiveInteger">
                        <minInclusive value="4"></minInclusive>
                        <maxInclusive value="15"></maxInclusive>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>


    <complexType name="PreciousGem">
        <complexContent>
            <extension base="tns:Gem">
                <sequence>
                    <element name="selling-only-on-auction" type="boolean"></element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="SemipreciousGem">
        <complexContent>
            <extension base="tns:Gem">
                <attribute name="rarity" use="optional" default="normal">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="frequent"></enumeration>
                            <enumeration value="normal"></enumeration>
                            <enumeration value="rare"></enumeration>
                        </restriction>
                    </simpleType>
                </attribute>
           </extension>
       </complexContent>
   </complexType>











</schema>

=== dorohovichandrey/xml_xsd_parsing/data/gems.xml
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/gems"
          xsi:schemaLocation="http://www.example.com/gems gem.xsd">
    <precious-gem gem-id="p1">
        <name>Andradit</name>
        <origin>
            <country>Belarus</country>
            <city>Soligorsk</city>
        </origin>
        <visual-parameters>
            <colour>Black</colour>
            <transparency-in-percents>100</transparency-in-percents>
            <number-of-verges>12</number-of-verges>
        </visual-parameters>
        <value-in-carat>3</value-in-carat>
        <selling-only-on-auction>true</selling-only-on-auction>
    </precious-gem>
    <precious-gem gem-id="p2">
        <name>Diamond</name>
        <origin>
            <country>Belarus</country>
            <city>Polotsk</city>
        </origin>
        <visual-parameters>
            <colour>White</colour>
            <transparency-in-percents>15</transparency-in-percents>
            <number-of-verges>5</number-of-verges>
        </visual-parameters>
        <value-in-carat>30</value-in-carat>
        <selling-only-on-auction>false</selling-only-on-auction>
    </precious-gem>
    <semiprecious-gem gem-id="sp1" rarity="rare">
        <name>Topas</name>
        <origin>
            <country>Russia</country>
            <city>Chelybinsk</city>
        </origin>
        <visual-parameters>
            <colour>Black</colour>
            <transparency-in-percents>20</transparency-in-percents>
            <number-of-verges>12</number-of-verges>
        </visual-parameters>
        <value-in-carat>3</value-in-carat>
    </semiprecious-gem>
    <semiprecious-gem gem-id="sp2">
        <name>Rubin</name>
        <origin>
            <country>Russia</country>
            <city>Chelybinsk</city>
        </origin>
        <visual-parameters>
            <colour>Black</colour>
            <transparency-in-percents>25</transparency-in-percents>
            <number-of-verges>9</number-of-verges>
        </visual-parameters>
        <value-in-carat>3</value-in-carat>
    </semiprecious-gem>
</gems>
